### ISSUE TITLE
Document that Java Topology API samples require toolkits in STREAMS_SPLPATH

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.iot#26]
Running the Java Topology API samples here: https://github.com/IBMStreams/streamsx.iot/blob/master/com.ibm.streamsx.iot/impl/java/src/com/ibm/streamsx/iot/sample/ requires that the com.ibm.streamsx.iot, com.ibm.streamsx.json, and com.ibm.streamsx.datatime toolkits are in the STREAMS_SPLPATH, otherwise they must be specified in the code similar to this: 

```
        SPL.addToolkit(topology, new File("/home/streamsadmin/git/streamsx.iot/com.ibm.streamsx.iot"));
        SPL.addToolkit(topology, new File("/home/streamsadmin/Downloads/IoTF/com.ibm.streamsx.json"));
        SPL.addToolkit(topology, new File("/home/streamsadmin/Downloads/IoTF/com.ibm.streamsx.datetime"));
```

**Comment by rnostream** [comment]
Close this one as streamsx.mqtt should be used directly
