### ISSUE TITLE
Sample application

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/streamsx.iot#30]
Need a sample application that can connect to Watson IoT with all components.

EventSubscribe() is not enough.

What about on premise ?
any tutorial ?

**Comment by ddebrunner** [comment]
The recommendation is to use the microservice approach and run the IotPlatform application to connect to Watson IotPlatform.

And then use the EventSubscribe operators etc.

Documented here:

http://ibmstreams.github.io/streamsx.iot/doc/spldoc/html/tk$com.ibm.streamsx.iot/ns$com.ibm.streamsx.iot.html

http://ibmstreams.github.io/streamsx.iot/doc/spldoc/html/tk$com.ibm.streamsx.iot/ns$com.ibm.streamsx.iot.watson.html

and

http://ibmstreams.github.io/streamsx.iot/doc/spldoc/html/tk$com.ibm.streamsx.iot/spl$com.ibm.streamsx.iot.watson.apps$IotPlatform.html

**Comment by ddebrunner** [comment]
There's a sample app that follows the pattern in the release:

http://ibmstreams.github.io/streamsx.iot/samples/CountEvents/doc/spldoc/html/index.html
