### ISSUE TITLE
Globalizing the toolkit

### ISSUE THREAD

**Issue by gertmark** [IBMStreams/streamsx.iot#47]
Provide log messages for different locales via unique message ids: German (de_DE), French (fr_FR), Italian (it_IT), Spanish (es_ES). Brazilian Portuguese (pt_BR), Japanese (ja_JP), Simplified Chinese (zh_CN), Russian (ru_RU), Traditional Chinese (zh_TW), Korean (ko_KR).

**Comment by schulz2** [comment]
I'm not allowed to branch in IBMStreams/streams.iot so I had to fork and delivered (will deliver) my changes into that. We need to merge all the stuff into IBMStreams/streamsx.iot:master later ...

**Comment by ddebrunner** [comment]
Standard development process is to work on a branch in your own fork and then create a pull request against master at IBMStreams/streamsx.iot.

**Comment by schulz2** [comment]
Hi Dan,
yes, that's what I finally ended up with. But the first toolkit I worked with was streamsx.json which doesn't enforce that behaviour and as far as I understood most of my colleagues here branch without forking within the toolkits they are responsible for. So being forced to fork confused ne in the first place.
Thanks for the clarification.

**Comment by schulz2** [comment]
I cannot assign myself to this issue. Is that wanted behaviour, too?

**Comment by ddebrunner** [comment]
That's just the way it is in github :-(

**Comment by chanskw** [comment]
I will see if I can add you as outside collaborator so we can assign it to you.  I will look at that in a bit.

**Comment by chanskw** [comment]
@schulz2, we also have you as @schubon on the committer team.  You sure you are using the right ID here?

**Comment by schulz2** [comment]
The schubon account got involved because of a misunderstanding between Gert and me. I want to only use the schulz2 account. Wasn't aware that schubon still was in the committers for IoT, but left the IoT now with that account. @chanskw : May I ask you to add the schulz2 account to the committers of the IoT Toolkit, please?

**Comment by chanskw** [comment]
I have added you to the IoT team @schulz2
