### ISSUE TITLE
[possible?] Typo in documentation regarding topics for events/commands

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.iot#58]
On this page:
http://ibmstreams.github.io/streamsx.iot/doc/spldoc/html/tk$com.ibm.streamsx.iot/spl$com.ibm.streamsx.iot$pubsub.html 
The doc says the topics are streamsx/iot/**device**/*
CommandsSubscribe: Subscribe to device commands published under the streams topic streamsx/**iotdevice**/commands/sent. (missing a '/' between iot and device)
EventsSubscribe: Subscribe to device events published under the streams topic streamsx/iot/**device**/events.
StatusesSubscribe: Subscribe to device status updates published under the streams topic streamsx/iot/**device**/statuses. 

Yet here, it says the topic is streamsx/iot/**devices**/
http://ibmstreams.github.io/streamsx.iot/doc/spldoc/html/tk$com.ibm.streamsx.iot/spl$com.ibm.streamsx.iot.watson.apps$IotPlatform.html
    Device events with streams topic: streamsx/iot/**devices**/events with schema of DeviceEvent
    Device commands with streams topic: streamsx/iot/**devices**/commands/sent with schema of DeviceCmd
    Device status updates with streams topic: streamsx/iot/**devices**/statuses with schema of DeviceStatus

Using streamsx/iot/devices did not work for me.

**Comment by rnostream** [comment]
Close this one as streamsx.mqtt should be used directly.
