### ISSUE TITLE
Support JSON commands

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.iot#60]
I have submitted pull request #59 as a suggestion.  I am using the Python API and since the IoTPlatform application only supports SPL commands, I can't directly publish commands from Python.
I have to publish my commands as JSON from Python and write a separate SPL application that subscribes to the JSON stream, and then publishes it as SPL
If this proposal is accepted then I don't have to have an intermediary.
The latest, as yet unreleased code in the Python API allows you to convert Python to SPL but I think this solution is better and prevents Python users from having to understand SPL Schemas.

**Comment by ddebrunner** [comment]
@natashadsilva FYI - Python developers will be understanding "structured schemas", not SPL schemas.

**Comment by rnostream** [comment]
#59 was merged
