### ISSUE TITLE
Quickstart composite no longer works

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.iot#62]
You cannot compile the Quickstart application because the signature of the getIotfUri function was changed:

https://github.com/IBMStreams/streamsx.iot/blob/e3e84c6f6c5751e1c5984c64db60ae4a631d23b5/com.ibm.streamsx.iot/com.ibm.streamsx.iot.watson/device.spl#L23

**Comment by rnostream** [comment]
Close this as streamsx.mqtt should be used directly.
