### ISSUE TITLE
Please include the IotPlatform and IotPlatformBluemix applications in the latest release

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.iot#66]
Hi, I just noticed that there are no binaries for the latest release of the IoT toolkit. This means that the  `IotPlatform.sab` application and the related helper applications have not been updated with the latest fixes, e.g. support for JSON commands.  Since these applications are crucial for users of the toolkit, could they please be added to the latest release? 
Thanks.

**Comment by schulz2** [comment]
Done
