### ISSUE TITLE
IotPlatform in standalone mode?

### ISSUE THREAD

**Issue by raghukiran1224** [IBMStreams/streamsx.iot#67]
Can the IotPlatform subscribe be used in standalone mode? It gives me a warning that the tuples cannot be imported/exported and fails with an error message after that.

**Comment by ddebrunner** [comment]
Since it uses publish/subscribe (import/export) to make tuples available to other applications running in an instance, no.

You could use the composites it uses and then add in your processing logic into the same standalone app.
