### ISSUE TITLE
Toolkit now depends on 4.2.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.iot#74]
The MQTT toolkit is dependent on 4.2 so this toolkit is now dependent on 4.2.

At least a couple of cleanup items:

- [x] Fix product version in info.xml (s)
- [ ] Can depend on application configurations so only a single IoTPlatform application is needed.

**Comment by rnostream** [comment]
@ddebrunner Yes, product version conflict is correct, but exits already before moving to streamsx.mqtt as streamsx.messaging moved to 4.2.0.0 already in v5.1.0 a year ago. I'll correct this. But for this I'll remove the new release (1.1.2) first, change the dependency and make a new toolkit version but now 1.2.0 to keep possibility open for patches for older product version (with numbering 1.1.x). 

What do you mean with the second point? This is not very clear to me.
