### ISSUE TITLE
Include pre-built `IoTPlatformBluemix` and other apps   for latest release

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.iot#83]
We have content on developerWorks, Watson Studio and Streamsdev that tell users to visit the release page and download the 
IotpSensors app, and the IoTPlatformBluemix app. These are not present in latest release. 

Please add the missing apps to match what was released in v1.0.2.
Is it possible to add these to the release creation Ant scripts?

**Comment by natashadsilva** [comment]
any updates on this? Our articles and doc recommend this path but in the latest release it isn't available, and a sab file that supports 4.3. is not available.

**Comment by rnostream** [comment]
Done. Pre-built package containing 4 apps build on Streams v4.3.x / RHEL7 x86-64. Hopefully the IOT toolkit remains the sole exception related to pre-build content. As any Streams installation is changing over the time related to Streams version and toolkit versions, pre-built items will hardly match w/o the  effort of numerous build configurations/items.
